name: flexi_form_field
description: "A flexible and customizable TextFormField widget for Flutter with built-in validation, formatting, mandatory fields, prefix/suffix icons, and more."
version: 4.0.1
homepage: https://github.com/manojprajapati1999/flexi_form_field
repository: https://github.com/manojprajapati1999/flexi_form_field

environment:
  sdk: ^3.5.0

platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux:

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  flutter_typeahead: ^6.0.0
  file_picker: ^8.1.2
  device_info_plus: ^11.1.1
  permission_manager: ^2.0.9
  image_picker: ^1.1.2
  animated_custom_dropdown: ^3.1.1
  flutter_switch: ^0.3.2
  marquee: ^2.2.3
  carousel_slider: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.svg